/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 beanbot.gltf --transform 
Files: beanbot.gltf [64.2MB] > C:\Users\jatin\Desktop\bean_bot\beanbot-transformed.glb [2.9MB] (95%)
Author: nataliedesign (https://sketchfab.com/nataliedesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bean-bot-9b1c86da128147e59bdbb9092ad40d2e
Title: Bean Bot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BeanBot(props) {
  const { nodes, materials } = useGLTF('/beanbot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sweep_Grey_0.geometry} material={materials.Grey} />
      <mesh geometry={nodes.Sweep_1_Blue_0.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Sweep_2_Brown_0.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Sweep_3_Green_0.geometry} material={materials.Green} />
      <mesh geometry={nodes.Sweep_4_Red_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Group24954_1_BeanBot_0.geometry} material={materials.BeanBot} position={[-0.018, 0.72, 0.506]} />
    </group>
  )
}

useGLTF.preload('/beanbot-transformed.glb')
