/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ninjabike.gltf --transform 
Files: ninjabike.gltf [28.61MB] > C:\Users\jatin\Desktop\ninja\ninjabike-transformed.glb [1.74MB] (94%)
Author: Moto3D (https://sketchfab.com/motocross3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kawasaki-ninja-h2-7ebe3980e2814030b5421430d04d3655
Title: Kawasaki Ninja H2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ninja(props) {
  const { nodes, materials } = useGLTF('/ninjabike-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0, 0.561, 0.705]} rotation={[2.709, 0, Math.PI]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} position={[0, 0.561, 0.705]} rotation={[2.709, 0, Math.PI]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.PaletteMaterial003} position={[0, 0.14, 0.088]} rotation={[3.134, 0, Math.PI]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Plastics} position={[0, 0.14, 0.088]} rotation={[3.134, 0, Math.PI]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Seat} position={[0, 0.14, 0.088]} rotation={[3.134, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/ninjabike-transformed.glb')
